import pickle
from deliqc.plotting import plot_point_mutation_rate

def plot(
        filename: "Pickle file generated by the run command.",
):
    with open(filename, "rb") as fh:
        sample = pickle.load(fh)

    plot_point_mutation_rate(sample)